<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WISDOM PANEL_selectparasite3</name>
   <tag></tag>
   <elementGuidId>8d20c3a8-588d-4e25-9080-b359004a61c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectparasite3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectparasite3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected-planobj</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;wisdom_Panel_tm&quot;,&quot;name&quot;:&quot;This DNA test screens for over 200 genetic disease mutations and detects more than 350 breeds, types and varieties using a cheek swab tissue sample. This type of early detection provides more information to you and your veterinarian to help plan for your pet’s health, behavior or training and nutrition needs. Test is only done once and does not renew.&quot;,&quot;htmlName&quot;:&quot;dwopt_dog-active-care_wisdom_Panel_tm&quot;,&quot;values&quot;:[{&quot;id&quot;:&quot;wisdom_Panel_tm_option&quot;,&quot;displayValue&quot;:&quot;WISDOM PANEL™&quot;,&quot;optionCategoryID&quot;:&quot;6&quot;,&quot;optionSortOrder&quot;:&quot;1&quot;,&quot;optionType&quot;:&quot;Other&quot;,&quot;optionGender&quot;:&quot;All&quot;,&quot;price&quot;:&quot;$6.75&quot;,&quot;priceValue&quot;:{},&quot;url&quot;:&quot;https://sfcc-uat.banfield.com/on/demandware.store/Sites-Banfield-Site/default/Product-Variation?dwopt_dog-active-care_adult_Canine_Neuter=adult_canine_neuter_option&amp;dwopt_dog-active-care_adult_Canine_Spay=adult_canine_spay_option&amp;dwopt_dog-active-care_flea_Heartworm_Prevention=flea_Heartworm_Prevention_option&amp;dwopt_dog-active-care_flea_Tick_Heartworm_Prevention_3_in_1=flea_Tick_Heartworm_Prevention_3_in_1_option&amp;dwopt_dog-active-care_flea_Tick_Prevention=flea_Tick_Prevention_option&amp;dwopt_dog-active-care_heartworm_Prevention=heartworm_Prevention_option&amp;dwopt_dog-active-care_wisdom_Panel_tm=wisdom_Panel_tm_option&amp;pid=dog-active-care&quot;}],&quot;selectedValueId&quot;:&quot;wisdom_Panel_tm_option&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-petid</name>
      <type>Main</type>
      <value>wisdom_Panel_tm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select parasite</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectparasite3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectparasite3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectparasite3&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectparasite3']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div[2]/div/div[2]/div/ul/div/table/tbody/tr/td[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/table/tbody/tr/td[2]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
