<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Flea, Tick  Heartworm Prevention (3 i_3d7b99</name>
   <tag></tag>
   <elementGuidId>f6194954-5c08-4d03-a4c6-930069679876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectparasite1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectparasite1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected-planobj</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;flea_Tick_Heartworm_Prevention_3_in_1&quot;,&quot;name&quot;:&quot;This category currently includes Simparica Trio that protects your pet from all 3 major parasites; fleas, ticks and heartworms. It comes in a chewable table that is to be given monthly.&quot;,&quot;htmlName&quot;:&quot;dwopt_dog-active-care_flea_Tick_Heartworm_Prevention_3_in_1&quot;,&quot;values&quot;:[{&quot;id&quot;:&quot;flea_Tick_Heartworm_Prevention_3_in_1_option&quot;,&quot;displayValue&quot;:&quot;Flea, Tick &amp; Heartworm Prevention (3 in 1)&quot;,&quot;optionCategoryID&quot;:&quot;4&quot;,&quot;optionSortOrder&quot;:&quot;1&quot;,&quot;optionType&quot;:&quot;Parasite&quot;,&quot;price&quot;:&quot;$24.50&quot;,&quot;priceValue&quot;:{},&quot;url&quot;:&quot;https://sfcc-uat.banfield.com/on/demandware.store/Sites-Banfield-Site/default/Product-Variation?dwopt_dog-active-care_adult_Canine_Neuter=adult_canine_neuter_option&amp;dwopt_dog-active-care_adult_Canine_Spay=adult_canine_spay_option&amp;dwopt_dog-active-care_flea_Heartworm_Prevention=flea_Heartworm_Prevention_option&amp;dwopt_dog-active-care_flea_Tick_Heartworm_Prevention_3_in_1=flea_Tick_Heartworm_Prevention_3_in_1_option&amp;dwopt_dog-active-care_flea_Tick_Prevention=flea_Tick_Prevention_option&amp;dwopt_dog-active-care_heartworm_Prevention=heartworm_Prevention_option&amp;dwopt_dog-active-care_wisdom_Panel_tm=wisdom_Panel_tm_option&amp;pid=dog-active-care&quot;}],&quot;selectedValueId&quot;:&quot;flea_Tick_Heartworm_Prevention_3_in_1_option&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-petid</name>
      <type>Main</type>
      <value>flea_Tick_Heartworm_Prevention_3_in_1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select parasite</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectparasite1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectparasite1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectparasite1&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectparasite1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div[2]/div/div[2]/div/div/table/tbody/tr/td[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
