<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Careers_fa fa-facebook</name>
   <tag></tag>
   <elementGuidId>3efec83e-5ca6-41ae-8b2a-4eedc343d9d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footercontent']/div/div/div/div[4]/ul/li/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-facebook</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-facebook</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footercontent&quot;)/div[@class=&quot;flat-footer&quot;]/div[@class=&quot;container footer-group-links border-bottom&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3&quot;]/ul[@class=&quot;social-links&quot;]/li[@class=&quot;slink&quot;]/a[1]/i[@class=&quot;fa fa-facebook&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footercontent']/div/div/div/div[4]/ul/li/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a/i</value>
   </webElementXpaths>
</WebElementEntity>
